QT.KAuth.VERSION = 5.115.0
QT.KAuth.MAJOR_VERSION = 5
QT.KAuth.MINOR_VERSION = 115
QT.KAuth.PATCH_VERSION = 0
QT.KAuth.name = KF5Auth
QT.KAuth.module = KF5Auth
QT.KAuth.defines = 
QT.KAuth.includes =  $$PWD/../../../../include/KF5/KAuthWidgets
QT.KAuth.private_includes =
QT.KAuth.libs = $$PWD/../../../../lib
QT.KAuth.depends = KAuthCore
QT.KAuth.module_config = 
