QT.KWindowSystem.VERSION = 5.115.0
QT.KWindowSystem.MAJOR_VERSION = 5
QT.KWindowSystem.MINOR_VERSION = 115
QT.KWindowSystem.PATCH_VERSION = 0
QT.KWindowSystem.name = KF5WindowSystem
QT.KWindowSystem.module = KF5WindowSystem
QT.KWindowSystem.defines = 
QT.KWindowSystem.includes =  $$PWD/../../../../include/KF5/KWindowSystem
QT.KWindowSystem.private_includes =
QT.KWindowSystem.libs = $$PWD/../../../../lib
QT.KWindowSystem.depends = gui
QT.KWindowSystem.module_config = 
