QT.KPty.VERSION = 5.115.0
QT.KPty.MAJOR_VERSION = 5
QT.KPty.MINOR_VERSION = 115
QT.KPty.PATCH_VERSION = 0
QT.KPty.name = KF5Pty
QT.KPty.module = KF5Pty
QT.KPty.defines = 
QT.KPty.includes =  $$PWD/../../../../include/KF5/KPty
QT.KPty.private_includes =
QT.KPty.libs = $$PWD/../../../../lib
QT.KPty.depends = core KCoreAddons
QT.KPty.module_config = 
