QT.KCodecs.VERSION = 5.115.0
QT.KCodecs.MAJOR_VERSION = 5
QT.KCodecs.MINOR_VERSION = 115
QT.KCodecs.PATCH_VERSION = 0
QT.KCodecs.name = KF5Codecs
QT.KCodecs.module = KF5Codecs
QT.KCodecs.defines = 
QT.KCodecs.includes =  $$PWD/../../../../include/KF5/KCodecs
QT.KCodecs.private_includes =
QT.KCodecs.libs = $$PWD/../../../../lib
QT.KCodecs.depends = core
QT.KCodecs.module_config = 
