QT.KIOWidgets.VERSION = 5.115.0
QT.KIOWidgets.MAJOR_VERSION = 5
QT.KIOWidgets.MINOR_VERSION = 115
QT.KIOWidgets.PATCH_VERSION = 0
QT.KIOWidgets.name = KF5KIOWidgets
QT.KIOWidgets.module = KF5KIOWidgets
QT.KIOWidgets.defines = 
QT.KIOWidgets.includes =  $$PWD/../../../../include/KF5/KIOWidgets
QT.KIOWidgets.private_includes =
QT.KIOWidgets.libs = $$PWD/../../../../lib
QT.KIOWidgets.depends = KIOGui KIOCore KBookmarks KXmlGui Solid
QT.KIOWidgets.module_config = 
