QT.KAuthCore.VERSION = 5.115.0
QT.KAuthCore.MAJOR_VERSION = 5
QT.KAuthCore.MINOR_VERSION = 115
QT.KAuthCore.PATCH_VERSION = 0
QT.KAuthCore.name = KF5AuthCore
QT.KAuthCore.module = KF5AuthCore
QT.KAuthCore.defines = 
QT.KAuthCore.includes =  $$PWD/../../../../include/KF5/KAuthCore $$PWD/../../../../include/KF5/KAuth
QT.KAuthCore.private_includes =
QT.KAuthCore.libs = $$PWD/../../../../lib
QT.KAuthCore.depends = core KCoreAddons
QT.KAuthCore.module_config = 
