QT.KTextEditor.VERSION = 5.115.0
QT.KTextEditor.MAJOR_VERSION = 5
QT.KTextEditor.MINOR_VERSION = 115
QT.KTextEditor.PATCH_VERSION = 0
QT.KTextEditor.name = KF5TextEditor
QT.KTextEditor.module = KF5TextEditor
QT.KTextEditor.defines = 
QT.KTextEditor.includes =  $$PWD/../../../../include/KF5/KTextEditor
QT.KTextEditor.private_includes =
QT.KTextEditor.libs = $$PWD/../../../../lib
QT.KTextEditor.depends = KParts
QT.KTextEditor.module_config = 
