QT.KTextWidgets.VERSION = 5.115.0
QT.KTextWidgets.MAJOR_VERSION = 5
QT.KTextWidgets.MINOR_VERSION = 115
QT.KTextWidgets.PATCH_VERSION = 0
QT.KTextWidgets.name = KF5TextWidgets
QT.KTextWidgets.module = KF5TextWidgets
QT.KTextWidgets.defines = 
QT.KTextWidgets.includes =  $$PWD/../../../../include/KF5/KTextWidgets
QT.KTextWidgets.private_includes =
QT.KTextWidgets.libs = $$PWD/../../../../lib
QT.KTextWidgets.depends = widgets SonnetUi KI18n
QT.KTextWidgets.module_config = 
