QT.KIconThemes.VERSION = 5.115.0
QT.KIconThemes.MAJOR_VERSION = 5
QT.KIconThemes.MINOR_VERSION = 115
QT.KIconThemes.PATCH_VERSION = 0
QT.KIconThemes.name = KF5IconThemes
QT.KIconThemes.module = KF5IconThemes
QT.KIconThemes.defines = 
QT.KIconThemes.includes =  $$PWD/../../../../include/KF5/KIconThemes
QT.KIconThemes.private_includes =
QT.KIconThemes.libs = $$PWD/../../../../lib
QT.KIconThemes.depends = widgets
QT.KIconThemes.module_config = 
