QT.KConfigGui.VERSION = 5.115.0
QT.KConfigGui.MAJOR_VERSION = 5
QT.KConfigGui.MINOR_VERSION = 115
QT.KConfigGui.PATCH_VERSION = 0
QT.KConfigGui.name = KF5ConfigGui
QT.KConfigGui.module = KF5ConfigGui
QT.KConfigGui.defines = 
QT.KConfigGui.includes =  $$PWD/../../../../include/KF5/KConfigGui
QT.KConfigGui.private_includes =
QT.KConfigGui.libs = $$PWD/../../../../lib
QT.KConfigGui.depends = gui xml KConfigCore
QT.KConfigGui.module_config = 
