QT.KArchive.VERSION = 5.115.0
QT.KArchive.MAJOR_VERSION = 5
QT.KArchive.MINOR_VERSION = 115
QT.KArchive.PATCH_VERSION = 0
QT.KArchive.name = KF5Archive
QT.KArchive.module = KF5Archive
QT.KArchive.defines = 
QT.KArchive.includes =  $$PWD/../../../../include/KF5/KArchive
QT.KArchive.private_includes =
QT.KArchive.libs = $$PWD/../../../../lib
QT.KArchive.depends = core
QT.KArchive.module_config = 
