QT.KWidgetsAddons.VERSION = 5.115.0
QT.KWidgetsAddons.MAJOR_VERSION = 5
QT.KWidgetsAddons.MINOR_VERSION = 115
QT.KWidgetsAddons.PATCH_VERSION = 0
QT.KWidgetsAddons.name = KF5WidgetsAddons
QT.KWidgetsAddons.module = KF5WidgetsAddons
QT.KWidgetsAddons.defines = 
QT.KWidgetsAddons.includes =  $$PWD/../../../../include/KF5/KWidgetsAddons
QT.KWidgetsAddons.private_includes =
QT.KWidgetsAddons.libs = $$PWD/../../../../lib
QT.KWidgetsAddons.depends = widgets
QT.KWidgetsAddons.module_config = 
