QT.KJS.VERSION = 5.115.0
QT.KJS.MAJOR_VERSION = 5
QT.KJS.MINOR_VERSION = 115
QT.KJS.PATCH_VERSION = 0
QT.KJS.name = KF5JS
QT.KJS.module = KF5JS
QT.KJS.defines = 
QT.KJS.includes =  $$PWD/../../../../include/KF5/KJS
QT.KJS.private_includes =
QT.KJS.libs = $$PWD/../../../../lib
QT.KJS.depends = core
QT.KJS.module_config = 
