QT.KCoreAddons.VERSION = 5.115.0
QT.KCoreAddons.MAJOR_VERSION = 5
QT.KCoreAddons.MINOR_VERSION = 115
QT.KCoreAddons.PATCH_VERSION = 0
QT.KCoreAddons.name = KF5CoreAddons
QT.KCoreAddons.module = KF5CoreAddons
QT.KCoreAddons.defines = 
QT.KCoreAddons.includes =  $$PWD/../../../../include/KF5/KCoreAddons
QT.KCoreAddons.private_includes =
QT.KCoreAddons.libs = $$PWD/../../../../lib
QT.KCoreAddons.depends = core
QT.KCoreAddons.module_config = 
