QT.KConfigCore.VERSION = 5.115.0
QT.KConfigCore.MAJOR_VERSION = 5
QT.KConfigCore.MINOR_VERSION = 115
QT.KConfigCore.PATCH_VERSION = 0
QT.KConfigCore.name = KF5ConfigCore
QT.KConfigCore.module = KF5ConfigCore
QT.KConfigCore.defines = 
QT.KConfigCore.includes =  $$PWD/../../../../include/KF5/KConfig $$PWD/../../../../include/KF5/KConfigCore
QT.KConfigCore.private_includes =
QT.KConfigCore.libs = $$PWD/../../../../lib
QT.KConfigCore.depends = core
QT.KConfigCore.module_config = 
