QT.KActivities.VERSION = 5.115.0
QT.KActivities.MAJOR_VERSION = 5
QT.KActivities.MINOR_VERSION = 115
QT.KActivities.PATCH_VERSION = 0
QT.KActivities.name = KF5Activities
QT.KActivities.module = KF5Activities
QT.KActivities.defines = 
QT.KActivities.includes =  $$PWD/../../../../include/KF5/KActivities
QT.KActivities.private_includes =
QT.KActivities.libs = $$PWD/../../../../lib
QT.KActivities.depends = 
QT.KActivities.module_config = 
