QT.SonnetCore.VERSION = 5.115.0
QT.SonnetCore.MAJOR_VERSION = 5
QT.SonnetCore.MINOR_VERSION = 115
QT.SonnetCore.PATCH_VERSION = 0
QT.SonnetCore.name = KF5SonnetCore
QT.SonnetCore.module = KF5SonnetCore
QT.SonnetCore.defines = 
QT.SonnetCore.includes =  $$PWD/../../../../include/KF5/Sonnet $$PWD/../../../../include/KF5/SonnetCore
QT.SonnetCore.private_includes =
QT.SonnetCore.libs = $$PWD/../../../../lib
QT.SonnetCore.depends = core
QT.SonnetCore.module_config = 
